"""Backward-compatible facade for the decomposed database layer.

Public imports should continue to use ``Code.db.database`` while implementation
details are split across focused repository modules.
"""

from __future__ import annotations

from Code.db.equipment_repo import (
    delete_equipment,
    get_all_equipment,
    get_distinct_equipment_values,
    get_equipment_by_id,
    get_equipment_by_uuid,
    get_equipment_stats,
    insert_equipment,
    search_equipment,
    update_equipment,
)
from Code.db.import_repo import (
    clear_all_data,
    get_all_import_issues,
    insert_import_issue,
    insert_raw_cells_batch,
    search_raw_cells,
    update_issue_status,
)
from Code.db.legacy_sync_queue import (
    count_pending_outbox_operations,
    delete_applied_op,
    delete_equipment_tombstone,
    delete_outbox_op,
    enqueue_outbox_op,
    enqueue_outbox_operation,
    get_applied_op,
    get_applied_operation,
    get_equipment_tombstone,
    get_outbox_op,
    get_outbox_operation,
    get_tombstone,
    has_applied_op,
    list_applied_ops,
    list_equipment_tombstones,
    list_outbox_operations,
    list_outbox_ops,
    mark_outbox_operation_applied,
    mark_outbox_operation_pending,
    mark_outbox_operation_superseded,
    record_applied_op,
    record_applied_operation,
    upsert_equipment_tombstone,
    upsert_tombstone,
    update_outbox_op,
    update_outbox_operation_status,
)
from Code.db.schema import create_tables, get_connection, get_database_path
from Code.db.snapshot_repo import (
    copy_database_snapshot,
    fetch_equipment_snapshot,
    fetch_equipment_tombstone_snapshot,
    fetch_import_issue_snapshot,
    fetch_raw_cell_snapshot,
    import_database_snapshot,
    replace_database_snapshot,
    replace_local_snapshot,
)
from Code.db.sync_state_repo import (
    ensure_client_identity,
    get_sync_state,
    load_sync_state,
    set_sync_state,
)

__all__ = [
    "clear_all_data",
    "copy_database_snapshot",
    "count_pending_outbox_operations",
    "create_tables",
    "delete_applied_op",
    "delete_equipment",
    "delete_equipment_tombstone",
    "delete_outbox_op",
    "enqueue_outbox_op",
    "enqueue_outbox_operation",
    "ensure_client_identity",
    "fetch_equipment_snapshot",
    "fetch_equipment_tombstone_snapshot",
    "fetch_import_issue_snapshot",
    "fetch_raw_cell_snapshot",
    "get_all_equipment",
    "get_all_import_issues",
    "get_applied_op",
    "get_applied_operation",
    "get_connection",
    "get_database_path",
    "get_distinct_equipment_values",
    "get_equipment_by_id",
    "get_equipment_by_uuid",
    "get_equipment_stats",
    "get_equipment_tombstone",
    "get_outbox_op",
    "get_outbox_operation",
    "get_sync_state",
    "get_tombstone",
    "has_applied_op",
    "import_database_snapshot",
    "insert_equipment",
    "insert_import_issue",
    "insert_raw_cells_batch",
    "list_applied_ops",
    "list_equipment_tombstones",
    "list_outbox_operations",
    "list_outbox_ops",
    "load_sync_state",
    "mark_outbox_operation_applied",
    "mark_outbox_operation_pending",
    "mark_outbox_operation_superseded",
    "record_applied_op",
    "record_applied_operation",
    "replace_database_snapshot",
    "replace_local_snapshot",
    "search_equipment",
    "search_raw_cells",
    "set_sync_state",
    "update_equipment",
    "update_issue_status",
    "update_outbox_op",
    "update_outbox_operation_status",
    "upsert_equipment_tombstone",
    "upsert_tombstone",
]